# Generated by Django 5.1.2 on 2025-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
