# Generated by Django 5.1.2 on 2025-05-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_itinerary_user_itinerary_firebase_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='firebase_uid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
