# Generated by Django 5.1.2 on 2025-05-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
