# Generated by Django 5.1.2 on 2025-05-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_activity_activity_alter_activity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
    ]
